---
- name: "Update apt packages"
  become: yes
  apt: 
    update_cache: yes
- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "Remove no longer needed dependencies"
  become: yes
  apt: 
    autoremove: yes
- name: "Install node"
  become: yes
  shell: |
    curl "https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh" -o install.sh
    chmod +x install.sh
    ./install.sh
    source ~/.bashrc
    nvm install v13.8.0
- name: "Install npm"
  become: yes
  apt: 
    name: ["npm"]
    state: latest
    update_cache: yes    
- name: "Install pm2"
  become: yes
  shell: |
    npm install -g pm2