---
- name: "Update apt packages"
  become: yes
  apt: 
    update_cache: yes
- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "Remove no longer needed dependencies"
  become: yes
  apt: 
    autoremove: yes
- name: "Download nvm install.sh"
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
    dest: ~/install.sh
- name: "change permission node"
# added exit 0 to mask the fail return code
  shell: |
    cd ~/
    chmod +x install.sh
- name: "Run modified Install script"
  copy:
    src: install_nvm.sh 
    dest: ~/install_nvm.sh
    mode: 0750  
- name: "run script"
  script: /home/ubuntu/install_nvm.sh 
#     # sh install.sh &>/dev/null || exit 0
- name: "Source bashrc"
  shell: |
    source ~/.bashrc
    nvm install v13.8.0
- name: "Install npm"
  become: yes
  apt: 
    name: ["npm"]
    state: latest
    update_cache: yes    
- name: "Install pm2"
  become: yes
  shell: |
    npm install -g pm2