---
- name: "Update apt packages"
  become: yes
  apt: 
    update_cache: yes
- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "Remove no longer needed dependencies"
  become: yes
  apt: 
    autoremove: yes
- name: "nodejs"
  become: yes
  shell: |
    source /home/ubuntu/.bashrc
    source /home/ubuntu/.profile    
    nvm install 13.8.0
    sudo npm install -g npm
  # curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  # sudo apt-get install -y nodejs
  # sudo npm install -g npm
  
- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present