---
- name: "Update apt packages"
  become: yes
  apt: 
    update_cache: yes
- name: "Upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "Remove no longer needed dependencies"
  become: yes
  apt: 
    autoremove: yes
- name: "Add nvm script to target"
  copy:
    src: install_nvm.sh
    dest: /home/ubuntu/
- name: "install nvm and npm"
  become: yes
  script: /home/ubuntu/install_nvm.sh
- name: "Add node script to target"
  copy:
    src: install_node.sh
    dest: /home/ubuntu/    
- name: "nodejs for ubun user"
  script: /home/ubuntu/install_node.sh
  # sudo npm install -g npm    
  # curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  # sudo apt-get install -y nodejs
  # sudo npm install -g npm
  
- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present