---
- name: "Create backend directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Push and extract artifact
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend
- name: "change directory to backend directory"
  become: yes
  shell: |
    cd ~/backend
- name: "Start the backend app"
  script: start_app.sh        
