---
- name: "Create backend directory"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Push and extract artifact
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
- name: "Start the App"
  become: yes
  shell: |
    cd /home/ubuntu/backend
    sudo -i -u ubuntu bash << EOF
    npm install
    npm audit fix 
    pm2 stop default
    pm2 start npm --start
    EOF        
