---
- name: "Create backend directory"
  file:
    path: ~/backend
    state: directory

- name: "Push backend artifact"
  copy:
    src: artifact.tar.gz 
    dst: ~/backend

- name: "Extract Artifact"
  shell: |
    tar -xzvf artifact.tar.gz
- name: "Start the App"
  shell: |
    npm install
    npm audit fix 
    pm2 stop default
    pm2 start npm --start        
