---
- name: "Create backend directory"
  file:
    path: ~/backend
    state: directory

- name: Push and extract artifact
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend
- name: "Start the App"
  shell: |
    cd ~/backend
    npm install
    npm audit fix 
    pm2 stop default
    pm2 start npm --start        
